Feat: Tuition Approval 👌
minikopi/sekolah pull request #137
Opened 2023-05-11 08:14 UTC by IndraA3

2023-05-11 08:28 UTC, backend-sempoa requested changes

2023-05-11 08:28 UTC, backend-sempoa commented on resources/views/layout/sidebar.blade.php
> -
ini kayaknya lebih enak klo gak dihapus jadi ada pemisah antara logo dan menu Dashboard.

2023-05-12 01:55 UTC, backend-sempoa commented on resources/views/layout/sidebar.blade.php
> -
yang ini @IndraA3

2023-05-12 04:02 UTC, IndraA3 commented on resources/views/layout/sidebar.blade.php
> -
[f8045b4](https://github.com/minikopi/sekolah/pull/137/commits/f8045b4b8b59d3f3882cccf4a7b0fe2224d4a273)
fixed

2023-05-12 04:04 UTC, backend-sempoa approved these changes

2023-05-12 04:04 UTC, merged